#import './fragments.gql'

mutation AuthorCreate($name: String!) {
  authorCreate(name: $name) {
    author {
      ...authorDetail
    }
  }
}

mutation TextCreate($title: String!, $authorSlug: String!, $raw: String!, $lines: [String]!) {
  textCreate(title: $title, authorSlug: $authorSlug, raw: $raw, lines: $lines) {
    text {
      lines
      raw
      ...textDetail
    }
  }
}

mutation TextAnnotationRelationCreate(
  $textSlug: String!,
  $textVersion: String!,
  $labelId: String!,
  $commentary: String!,
  $textIndex: Int!,
) {
  textAnnotationRelationCreate (
    textSlug: $textSlug,
    textVersion: $textVersion,
    labelId: $labelId,
    commentary: $commentary,
    textIndex: $textIndex
  ) {
    textAnnotationRelation {
      commentary
      textIndex
      label {
        value
      }
    }
  }
}
