#import './fragments.gql'

mutation AuthorCreate($name: String!) {
  authorCreate(name: $name) {
    author {
      ...authorDetail
    }
  }
}

mutation TextCreate($title: String!, $authorSlug: String!, $raw: String!, $lines: [String]!) {
  textCreate(title: $title, authorSlug: $authorSlug, raw: $raw, lines: $lines) {
    text {
      lines
      raw
      ...textDetail
    }
  }
}

mutation TextAnnotationRelationCreate(
  $textSlug: String!,
  $textVersion: String!,
  $annotationId: Int!,
  $commentary: String!,
  $textStartIndex: Int!,
  $textEndIndex: Int!
) {
  textAnnotationRelationCreate (
    textSlug: $textSlug,
    textVersion: $textVersion,
    annotationId: $annotationId,
    commentary: $commentary,
    textStartIndex: $textStartIndex,
    textEndIndex: $textEndIndex
  ) {
    textAnnotationRelation {
      commentary
      textStartIndex
      textEndIndex
      annotation {
        value
      }
    }
  }
}

mutation TextAnnotationRelationUpdate(
  $id: ID!,
  $textSlug: String!,
  $textVersion: String!,
  $annotationId: Int!,
  $commentary: String!,
  $textStartIndex: Int!,
  $textEndIndex: Int!
) {
  textAnnotationRelationUpdate (
    id: $id,
    textSlug: $textSlug,
    textVersion: $textVersion,
    annotationId: $annotationId,
    commentary: $commentary,
    textStartIndex: $textStartIndex,
    textEndIndex: $textEndIndex
  ) {
    textAnnotationRelation {
      commentary
      textStartIndex
      textEndIndex
      annotation {
        value
      }
    }
  }
}
